Panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint5: {p: 250, d: 15, i: 0, i_clamp: 1}
    panda_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_joint7: {p: 50,  d: 5,  i: 0, i_clamp: 1}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
